### ISSUE TITLE
Shareable Executor

### ISSUE THREAD

**Issue by huntc** [huntc/landlord#5]
From Jason Zaugg:

> An important thing to consider is whether the landlord or the tenants are in control on the threads. If the heap requirements are low, the next dominant factor in footprint is thread stacks. If each tenant creates a thread pool, many of the gains of communal living are gone.

We should provide a Java `Executor` for the purposes of async/non-blocking operations that programs may leverage and thus share threads. For example, In the case of Akka, which is what my hosted programs are written to use, I can at least tell the ActorSystem what Dispatcher to use as a default. Unfortunately, Akka doesn't appear to give me control over providing an existing Dispatcher object for blocking operations. But then, blocking operations should be avoidable for the use-cases I have in mind (low powered, diskless routers and sensors).

**Comment by huntc** [comment]
By way of a solution, perhaps we should use JNDI e.g. landlord could provide the following executor namespace:

```
landlord:/executors/async-nonblocking
```

**Comment by jousby** [comment]
re jndi what where you thinking for the service provider implementation?
options:
- run an LDAP server in process and pull in an open source ldap project. 
- start the 'rmiregistry' process that is part of the jdk 
- others.

My thinking at this point is to try running an ldap server in process and see what this does to the memory usage of the landloard daemon.

**Comment by huntc** [comment]
Good question. I was thinking along the lines of implementing the JNDI SPI. I think our needs are small and shouldn’t warrant an LDAP server.

**Comment by huntc** [comment]
I'll leave this issue open for a while, but I think it'll be hard to resolve. Each thread requires a default context class loader. So, although threads could be shared across classloader code, setting up the right context class loader will be more of a challenge.

**Comment by huntc** [comment]
Closing this as I'm not going to attempt to resolve it due to there being no apparent solution.
